[pytest]
DJANGO_SETTINGS_MODULE = django_project.settings
pythonpath = .
testpaths = tests
markers =
    unit: Модульные тесты (не требуют БД)
    integration: Интеграционные тесты (требуют БД)
    views: Тесты представлений